version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 6
    allow:
      - dependency-type: "production"
