reviewers:
  groups:
    developers:
      - jmtaber129
      - igorlesnenko
      - nickoferrall
      - BartoszJarocki
    maintainers:
      - mattkrick
      - Dschoordsch
    data:
      - tianrunhe
      - tghanken
    designers:
      - ackernaut
      - enriquesanchez
    devops:
      - rafaelromcar-parabol
      - adaniels-parabol
    none:

  per_author:
    developers:
      - none
    maintainers:
      - none
    data:
      - none
    designers:
      - none

  defaults:
    - developers

files:
  '**/migrations/**':
    - data
  '**/analytics/**':
    - data
options:
  ignore_draft: true
  ignored_keywords:
    - WIP
  number_of_reviewers: 1
