reviewers:
  groups:
    reviewers:
    maintainers:
      - mattkrick
      - Dschoordsch
    designers:
      - ackernaut
    devops:
      - rafaelromcar-parabol
    none:

  per_author:
    reviewers:
      - none
    maintainers:
      - none
    designers:
      - none
    devops:
      - none

  defaults:
    - maintainers

files:
  "docker/**":
    - devops
  ".env.example":
    - devops
  "release-please-config.json":
    - devops
options:
  ignore_draft: true
  ignored_keywords:
    - WIP
    - chore(release)
  number_of_reviewers: 1
