reviewers:
  groups:
    developers:
      - jmtaber129
      - igorlesnenko
      - nickoferrall
      - BartoszJarocki
    maintainers:
      - mattkrick
      - Dschoordsch
    data:
      - tianrunhe
      - tghanken
    designers:
      - ackernaut
      - enriquesanchez
    devops:
      - rafaelromcar-parabol
      - adaniels-parabol
      - dbumblis-parabol
    none:

  per_author:
    developers:
      - none
    maintainers:
      - none
    data:
      - none
    designers:
      - none
    devops:
      - none

  defaults:
    - developers

files:
  "**/migrations/**":
    - data
  "**/analytics/**":
    - data
  ".env.example":
    - devops
options:
  ignore_draft: true
  ignored_keywords:
    - WIP
    - chore(release)
  number_of_reviewers: 1
