packages:
  - packages/*

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - nest-graphql-endpoint
  - '@tiptap/*'
  - fast-xml-parser

allowBuilds:
  '@datadog/native-appsec': true
  '@datadog/native-iast-taint-tracking': true
  '@datadog/native-metrics': true
  '@datadog/pprof': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  core-js: true
  core-js-pure: true
  cpu-features: true
  dd-trace: true
  es5-ext: true
  esbuild: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  sharp: true
  ssh2: true
  styled-components: true

overrides:
  typescript: '^7.0.2'
  hoist-non-react-statics: '^3.3.0'
  '@types/react': '^18.3.0'
  '@types/react-dom': '^18.3.0'
  clean-css: '^5.2.2'
  node-forge: '^1.3.2'
  glob-parent: '^6.0.2'
  node-pre-gyp: '^0.17.0'
  ansi-regex: '^5.0.1'
  json-schema: '^0.4.0'
  nanoid: '^3.3.18'
  '@xmldom/xmldom': '^0.8.15'
  node-gyp: '^8.4.1'
  simple-get: '^4.0.1'
  caniuse-lite: '~1.0.0'
  git-url-parse: 12.0.0
  fbjs: '^3.0.0'
  parse-url: '^8.1.0'
  fast-xml-parser: '^5.8.0'
  recursive-readdir: '^2.2.3'
  redux-offline: 'enahum/redux-offline#885024de96b6ec73650c340c8928066585c413df'
  react: '^18.3.1'
  react-dom: '^18.3.1'
  '@babel/runtime': '^7.27.1'
  'brace-expansion@1.1.11': 1.1.12
  'brace-expansion@2.0.1': 2.0.2
  source-map: 0.7.6
  qs: '^6.14.1'
  handlebars: '^4.7.9'
  brace-expansion: '^1.1.18'
  '@graphql-tools/utils': '^11.0.1'
  'pm2>js-yaml': '^4.3.2'
  '@emotion/is-prop-valid': '-'

patchedDependencies:
  '@sereneinserenade/tiptap-search-and-replace@0.1.1': patches/@sereneinserenade__tiptap-search-and-replace@0.1.1.patch
  '@tiptap/core@3.31.2': patches/@tiptap__core@3.31.2.patch
