// Generates the design-sync entry barrel, componentSrcMap, group-stub docs,
// and docsMap from a curated manifest. For each source file, extracts exported
// React components (PascalCase const/function/class or `export default`),
// skipping hooks (use*), contexts (*Context), types, and utils.
//
// Manifest (.design-sync/manifest.json):
//   { "groups": [ { "name": "Team Dashboard", "dirs": [..], "files": [..],
//                   "includeRelay": false } ] }
// Paths are relative to packages/client (== PKG_DIR).
//
// Emits:
//   packages/client/.ds-entry.tsx          — barrel re-exporting every component
//   .design-sync/groups/<slug>.md          — one frontmatter-only stub per group
//   config.componentSrcMap, config.docsMap — merged into .design-sync/config.json
import {writeFileSync, existsSync, readdirSync, readFileSync, mkdirSync, rmSync} from 'node:fs'
import {relative, resolve, join} from 'node:path'
import {Project, Node, ts} from 'ts-morph'

const REPO = resolve(process.argv[2] || '.')
const manifestArg = process.argv[3]
if (!manifestArg) {
  console.error('usage: gen.mjs <repo> <manifest.json>')
  process.exit(1)
}
const PKG_DIR = resolve(REPO, 'packages/client')
const manifest = JSON.parse(readFileSync(resolve(REPO, manifestArg), 'utf8'))
const EXCLUDE = new Set(manifest.exclude ?? [])

const SKIP_NAME = /^(use[A-Z]|.*Context$|.*Props$|.*Provider$)/
const UTIL = new Set(['cn', 'cx', 'twStyled', 'forwardRadix', 'forwardRef'])
const isComp = (n) => /^[A-Z][A-Za-z0-9]*$/.test(n) && !SKIP_NAME.test(n) && !UTIL.has(n)
const RELAY_RX = /graphql`|useFragment\b|usePreloadedQuery\b|useLazyLoadQuery\b|createFragmentContainer\b|createPaginationContainer\b|usePaginationFragment\b|useRefetchableFragment\b|useQueryLoaderNow\b/
const slug = (s) => s.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')

const UTIL_FILE = /(?:^|\/)(cn|cx|twStyled|forwardRadix)\.tsx?$/
const walk = (abs, acc) => {
  for (const e of readdirSync(abs, {withFileTypes: true})) {
    if (e.name === 'node_modules' || e.name.startsWith('.') || e.name === '__generated__') continue
    const p = join(abs, e.name)
    if (e.isDirectory()) walk(p, acc)
    else if (/\.(tsx|jsx)$/.test(e.name) && !/\.(stories|test|spec)\./.test(e.name) && !UTIL_FILE.test(p)) acc.push(p)
  }
  return acc
}

// Resolve a manifest group's files (package-relative), applying the relay skip.
function groupFiles(g) {
  const out = []
  for (const d of g.dirs ?? []) {
    const abs = resolve(PKG_DIR, d)
    if (!existsSync(abs)) { console.error(`! missing dir: ${d}`); continue }
    out.push(...walk(abs, []).map((p) => relative(PKG_DIR, p)))
  }
  for (const f of g.files ?? []) {
    const abs = resolve(PKG_DIR, f)
    if (!existsSync(abs)) { console.error(`! missing file: ${f}`); continue }
    out.push(f)
  }
  // relay skip unless the group opts in
  return out.filter((rel) => {
    if (g.includeRelay) return true
    const src = readFileSync(resolve(PKG_DIR, rel), 'utf8')
    if (RELAY_RX.test(src)) { console.error(`  · skip [relay]: ${rel}`); return false }
    return true
  })
}

const project = new Project({
  skipAddingFilesFromTsConfig: true,
  compilerOptions: {jsx: ts.JsxEmit.Preserve, allowJs: true, skipLibCheck: true}
})

const fileBase = (p) => p.split('/').pop().replace(/\.(tsx|jsx|ts|js)$/, '')

// name -> {file (pkg-rel), isDefault, group}
const found = new Map()
const collisions = []
for (const g of manifest.groups) {
  for (const rel of groupFiles(g)) {
    const abs = resolve(PKG_DIR, rel)
    const sf = project.addSourceFileAtPathIfExists(abs)
    if (!sf) continue
    for (const [name, decls] of sf.getExportedDeclarations()) {
      const isDefault = name === 'default'
      const real = isDefault
        ? decls.map((d) => d.getName?.()).find((n) => n && n !== 'default') || fileBase(rel)
        : name
      if (!isComp(real)) continue
      const isValueDecl = decls.some(
        (d) =>
          Node.isVariableDeclaration(d) ||
          Node.isFunctionDeclaration(d) ||
          Node.isClassDeclaration(d) ||
          (isDefault && (Node.isIdentifier(d) || Node.isCallExpression(d) || Node.isExportAssignment(d)))
      )
      if (!isValueDecl && !isDefault) continue
      if (EXCLUDE.has(real)) continue
      if (found.has(real)) {
        if (found.get(real).file !== rel) collisions.push(`${real}: ${found.get(real).file} vs ${rel}`)
        continue
      }
      found.set(real, {file: rel, isDefault, group: g.name})
    }
  }
}

// ── barrel ──
const byFile = new Map()
for (const [name, {file, isDefault}] of found) {
  if (!byFile.has(file)) byFile.set(file, [])
  byFile.get(file).push({name, isDefault})
}
const barrelDir = PKG_DIR
const lines = ['// AUTO-GENERATED by .ds-sync/gen.mjs — do not edit by hand', '']
for (const [file, names] of byFile) {
  const spec = './' + relative(barrelDir, resolve(PKG_DIR, file)).replace(/\.(tsx|jsx)$/, '')
  const named = names.filter((n) => !n.isDefault).map((n) => n.name)
  const def = names.find((n) => n.isDefault)
  const clauses = []
  if (def) clauses.push(`default as ${def.name}`)
  clauses.push(...named)
  lines.push(`export {${clauses.join(', ')}} from '${spec}'`)
}
writeFileSync(resolve(PKG_DIR, '.ds-entry.tsx'), lines.join('\n') + '\n')

// ── group stubs + docsMap ──
const groupsDir = resolve(REPO, '.design-sync/groups')
rmSync(groupsDir, {recursive: true, force: true})
mkdirSync(groupsDir, {recursive: true})
const groupSlugs = new Map()
for (const g of manifest.groups) {
  const s = slug(g.name)
  groupSlugs.set(g.name, s)
  writeFileSync(join(groupsDir, `${s}.md`), `---\ncategory: ${g.name}\n---\n`)
}

// ── merge into config ──
const srcMap = {}
const docsMap = {}
for (const [name, {file, group}] of [...found].sort((a, b) => a[0].localeCompare(b[0]))) {
  srcMap[name] = relative(PKG_DIR, resolve(PKG_DIR, file))
  docsMap[name] = `../../.design-sync/groups/${groupSlugs.get(group)}.md`
}
const cfgPath = resolve(REPO, '.design-sync/config.json')
const cfg = JSON.parse(readFileSync(cfgPath, 'utf8'))
cfg.componentSrcMap = srcMap
cfg.docsMap = docsMap
writeFileSync(cfgPath, JSON.stringify(cfg, null, 2) + '\n')

const byGroup = {}
for (const [, {group}] of found) byGroup[group] = (byGroup[group] ?? 0) + 1
console.error(`✓ ${found.size} components → barrel + config (componentSrcMap, docsMap)`)
for (const [g, n] of Object.entries(byGroup)) console.error(`    ${g}: ${n}`)
if (collisions.length) {
  console.error(`! ${collisions.length} collisions (kept first):`)
  for (const c of collisions.slice(0, 20)) console.error(`  ${c}`)
}
