const dataFieldsToSerialize = [
  'channelId',
  'message.data.notificationId',
  'message.data.taskIds',
  'message.data.teamId',
  'message.data.teamMemberId',
  'message.data.userId',
  'message.data.invitationIds',
  'message.data.inviteeApprovedNotificationIds',
  'message.data.removedOrgApprovals.approvedBy',
  'message.data.removedOrgApprovals.email',
  'message.data.removedOrgApprovals.id',
  'message.data.removedOrgApprovals.orgId',
  'message.data.removedOrgApprovals.teamId',
  'message.data.removedRequestNotifications.id',
  'message.data.removedRequestNotifications.inviteeEmail',
  'message.data.removedRequestNotifications.inviterUserId',
  'message.data.removedRequestNotifications.orgId',
  'message.data.removedRequestNotifications.teamId',
  'message.data.removedRequestNotifications.userIds',
  'message.data.teamIdFilter',
  'message.data.teamInviteNotificationIds',
  'message.data.removedOrgApprovals.createdAt',
  'message.data.removedOrgApprovals.teamId',
  'message.data.deniedNotificationIds',
  'message.data.removedOrgApprovalIds',
  'message.data.notificationIds'
];

export default dataFieldsToSerialize;
