import {WebAuth} from 'auth0-js'
import makeHref from 'universal/utils/makeHref'

/*
 * Requires sync webAuth to ensure it is not caught by a popup blocker.
 * Popup blockers usually ignore trusted user events (like clicks)
 * But doing asynchronous things within the click handler can cause a false positive
 */

const auth0Authorize = async (webAuth: WebAuth, loginHint?: string) => {
  return new Promise((resolve, reject) => {
    webAuth.popup.authorize(
      {
        connection: 'google-oauth2',
        redirectUri: makeHref('/oauth-redirect'),
        responseType: 'token',
        state: Math.random()
          .toString(36)
          .substring(5),
        // @ts-ignore
        login_hint: loginHint
      },
      (err, res) => {
        if (err) {
          if (err.name === 'SyntaxError') {
            console.error(err) // IGNORE SyntaxError which are generated by external extensions
          } else {
            const errorMsg = err.errorDescription || err.original
            reject(errorMsg)
          }
        } else {
          resolve(res)
        }
      }
    )
  })
}

export default auth0Authorize
