import {Client} from 'pg'
import getPgConfig from '../getPgConfig'

export async function up() {
  const client = new Client(getPgConfig())
  await client.connect()
  await client.query(`
    CREATE TABLE "UserInteractions" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      "createdById" VARCHAR(100) NOT NULL REFERENCES "User"("id"),
      "receivedById" VARCHAR(100) NOT NULL REFERENCES "User"("id"),
      "emoji" VARCHAR(100) NOT NULL,
      "emojiName" VARCHAR(100) NOT NULL
    );
  `)

  await client.end()
}

export async function down() {
  const client = new Client(getPgConfig())
  await client.connect()
  await client.query(`DROP TABLE IF EXISTS "UserInteractions";`)
  await client.end()
}
