import {Client} from 'pg'
import getPgConfig from '../getPgConfig'

export async function up() {
  const client = new Client(getPgConfig())
  await client.connect()
  await client.query(`
    CREATE TABLE IF NOT EXISTS "TeamPromptQuestion" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
      "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
      "templateId" VARCHAR(100) NOT NULL REFERENCES "MeetingTemplate"("id") ON DELETE CASCADE,
      "question" VARCHAR(1000) NOT NULL
    );

    ALTER TABLE "TeamPromptResponse"
      ADD COLUMN IF NOT EXISTS "questionId" INT REFERENCES "TeamPromptQuestion"("id") ON DELETE CASCADE;
  `)

  await client.end()
}

export async function down() {
  const client = new Client(getPgConfig())
  await client.connect()
  await client.query(`
    ALTER TABLE "TeamPromptResponse"
      DROP COLUMN IF EXISTS "questionId";

    DROP TABLE IF EXISTS "TeamPromptQuestion";
  `)
  await client.end()
}
