FROM node:16.13.2 as base

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

RUN mkdir -p /parabol/node_modules && mkdir -p /home/node/.npm-global

WORKDIR /parabol/
ADD package.json .
ADD yarn.lock .
COPY . .

FROM base as prod
RUN yarn install --frozen-lockfile
RUN yarn build
RUN cp docker/entrypoint.prod.sh /bin/entrypoint
RUN chmod +x /bin/entrypoint
EXPOSE 80
ENTRYPOINT [ "entrypoint" ]
CMD ["yarn", "start"]
