import {PALETTE} from './paletteV2'

const palettePickerOptions = [
  PALETTE.PROMPT_RED,
  PALETTE.PROMPT_ORANGE,
  PALETTE.PROMPT_YELLOW,
  PALETTE.PROMPT_LIGHT_GREEN,
  PALETTE.PROMPT_GREEN,
  PALETTE.PROMPT_CYAN,
  PALETTE.PROMPT_LIGHT_BLUE,
  PALETTE.PROMPT_BLUE,
  PALETTE.PROMPT_PURPLE,
  PALETTE.PROMPT_VIOLET,
  PALETTE.PROMPT_FUCHSIA,
  PALETTE.PROMPT_PINK
]

export {palettePickerOptions}
