version: '3.7'

services:
  db:
    image: rethinkdb:latest
    restart: always
    ports:
      - '8080:8080'
      - '29015:29015'
      - '28015:28015'
    volumes:
      - ./rethink-data:/data
    networks:
      - parabol-network
  postgres:
    image: postgres:12.10
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - './postgres.conf:/usr/local/etc/postgres/postgres.conf'
      - './postgres-data/pgdata:/var/lib/postgresql/data'
    command: 'postgres -c config_file=/usr/local/etc/postgres/postgres.conf'
    networks:
      - parabol-network
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
    networks:
      - parabol-network
  app:
    image: #image:tag
    restart: always
    env_file: .env
    command: bash -c "yarn db:migrate && yarn pg:migrate up && NODE_ENV=production && yarn start"
    ports:
      - '3000:3000'
    volumes:
      - './.env:/parabol/.env'
    depends_on:
      - db
      - redis
      - postgres
    networks:
      - parabol-network
networks:
  parabol-network:
