#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn postcheckout

DELETED_POSTGRES_MIGRATIONS=$(git diff $1 $2 --name-only --diff-filter=D -- packages/server/postgres/migrations/)
if [ ! -z "$DELETED_POSTGRES_MIGRATIONS" ]; then
    CURRENT_BRANCH=$(git branch --show-current)
    NUM_POSTGRES_MIGRATIONS=$(echo $DELETED_POSTGRES_MIGRATIONS | wc -w)
    echo "WARNING: You're leaving behind the following migrations not present on the current branch:"
    echo
    for X in $DELETED_POSTGRES_MIGRATIONS; do
        echo "  ${X##*/}"
    done
    echo
    echo "Consider running:"
    echo
    echo "  git checkout ${1} &&"
    if [ ! -z "$DELETED_POSTGRES_MIGRATIONS" ]; then
        echo "  yarn kysely migrate:down ${NUM_POSTGRES_MIGRATIONS} &&"
    fi
    echo "  git checkout ${CURRENT_BRANCH:-$2}"
    echo
fi
