#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn run improved-yarn-audit --min-severity moderate

vulnerabilities=$?
if [ $vulnerabilities -eq 0 ]; then
  echo "No vulnerabilities found."
else
  echo "Vulnerabilities moderate or above found. Resolve issues before commiting code. See console output for more details."
  exit 1
fi

yarn run precommit
