name: Create a new issue from Datadog

on:
  workflow_dispatch:
    inputs:
      issueLink:
        description: 'Datadog issueLink'
        required: true
        type: string
      errorType:
        description: 'Error type'
        required: true
        type: string
      errorMessage:
        description: 'Error message'
        required: true
        type: string
      errorStack:
        description: 'Error stack'
        required: true
        type: string

permissions:
  issues: write
  contents: read

jobs:
  create-issue:
    runs-on: ubuntu-latest
    name: Create a new issue from Datadog
    steps:
      - name: Create a new issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueLink = '${{ inputs.issueLink }}';
            const errorType = '${{ inputs.errorType }}';
            const errorMessage = '${{ inputs.errorMessage }}';
            const errorStack = '${{ inputs.errorStack }}';

            const issueLinkURL = new URL(issueLink);
            const searchPattern = `${issueLink.split('?')[0]}?.*issueId=${issueLinkURL.searchParams.get('issueId')}`
            const existingIssues = await github.rest.search.issues({
              q: `repo:${context.repo.owner}/${context.repo.repo} is:issue '${searchPattern}"`,
              per_page: 10
            });
            console.log(`Found ', JSON.stringify(existingIssues.data, null, 2));
            const existingCount = existingIssues.data.total_count;
            if (existingCount > 0) {
              console.log(`An issue with the same link already exists. Skipping creation.`);
              return;
            }

            const issueTitle = `${errorType}: ${errorMessage.substring(0,120)}${errorMessage.length > 120 ? '...' : ''}`;
            const issueBody = `${errorType}\n\n${errorMessage}\n\n\`\`\`${errorStack}\`\`\`\n\n[see Datadog](${issueLink}) 🔒`;
            const newIssue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['bug']
            });


