name: Create a new issue from Datadog

on:
  workflow_dispatch:
    inputs:
      issueId:
        description: 'Datadog issue ID'
        required: true
        type: string
      issueLink:
        description: 'Datadog issue link'
        required: true
        type: string
      errorType:
        description: 'Error type'
        required: true
        type: string
      errorMessage:
        description: 'Error message'
        required: true
        type: string
      errorStack:
        description: 'Error stack'
        required: true
        type: string

permissions:
  issues: write
  contents: read

jobs:
  create-issue:
    runs-on: ubuntu-latest
    name: Create a new issue from Datadog
    steps:
      - name: Create a new issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueId = '${{ inputs.issueId }}';
            const issueLink = '${{ inputs.issueLink }}';
            const errorType = '${{ inputs.errorType }}';
            const errorMessage = '${{ inputs.errorMessage }}';
            const errorStack = '${{ toJSON(inputs.errorStack) }}';
            const existingIssues = await github.rest.search.issuesAndPullRequests({
              q: `repo:${context.repo.owner}/${context.repo.repo} is:issue "${issueId}"`,
              per_page: 10
            });
            console.log('Found ', JSON.stringify(existingIssues.data, null, 2));
            const existingCount = existingIssues.data.total_count;
            if (existingCount > 0) {
              console.log('An issue with the same link already exists. Skipping creation.');
              return;
            }
            const issueTitle = `${errorType}: ${errorMessage.substring(0,120)}${errorMessage.length > 120 ? '...' : ''}`;
            const issueBody = `${errorType}\n\n${errorMessage}\n\n\`\`\`${errorStack}\`\`\`\n\n[see Datadog ${issueId}](${issueLink}) 🔒`;
            const newIssue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['bug']
            });


