on:
  push:
    branches:
      - staging
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          default-branch: staging
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}

