on:
  push:
    branches:
      - production
name: release-hotfix
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          default-branch: production
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
