name: Pull Request Stats

on:
  schedule:
    - cron: '54 14 * * 5'

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.16.0"
      - name: Run pull request stats
        run: |
          yarn
          yarn ts-node scripts/reviewStats.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          REPO: ${{ github.repository }}
          TIME_DIFF: 7d
