name: Pull Request Stats

on:
  schedule:
    - cron: '54 14 * * 5'

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: Dschoordsch/slack-review-stats@v1.0.0
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}

