name: Pull Request Stats

on:
  pull_request:
    types: [labeled]

jobs:
  stats:
    if: ${{ github.event.label.name == 'pr_stats' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          charts: true
          sort-by: 'TIME'
