name: Update Snyk PR to add pnpm-lock.yaml

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-snyk-pr:
    if: contains(github.event.pull_request.title, '[Snyk]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create one
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup environment variables
        run: |
          ACTION_VERSION=$(grep '"version":' package.json | cut -d\" -f4)
          echo "ACTION_VERSION=${ACTION_VERSION}" >> $GITHUB_ENV
          echo "NODE_VERSION=$(jq -r -j '.engines.node|ltrimstr("^")' package.json)" >> $GITHUB_ENV

          DOCKER_REPOSITORY_FOR_REF=${{ secrets.GCP_AR_PARABOL_DEV }}
          echo "DOCKER_REPOSITORY_FOR_REF=${{ secrets.GCP_AR_PARABOL_DEV }}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Get cached node modules
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: node_modules-${{ runner.arch }}-${{ env.NODE_VERSION }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        # pnpm has a bug that resolves git+https to ssh
        run: |
          git config --global url."https://github.com/enahum/redux-offline.git".insteadOf git@github.com:enahum/redux-offline.git
          pnpm install --frozen-lockfile

      - name: Commit pnpm-lock.yaml to the PR branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add pnpm-lock.yaml
          git commit -m "Update pnpm-lock.yaml" || echo "No changes to commit"
          git push
